In [52]:
import json
import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy
import pdb

In [53]:
df = pd.read_csv('commondata/ELSI_csv_California_district_enrollment_ethnicity_2016_2017_G6-9.csv', error_bad_lines=False, delimiter=',')

In [54]:
df.head(4)

,Agency Name,State Name [District] Latest available year,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,...,Grade 8 Students - White [District] 2016-17,Grade 8 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 8 Students - Two or More Races [District] 2016-17,Grade 9 Students - American Indian/Alaska Native [District] 2016-17,Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17
0,ABC UNIFIED,California,3,562,777,116,110,10,53,4,...,109,16,31,8,608,710,171,92,14,37
1,ACALANES UNION HIGH,California,†,†,†,†,†,†,†,†,...,†,†,†,1,200,129,27,896,3,110
2,ACKERMAN CHARTER,California,1,2,5,1,49,–,4,–,...,44,–,2,†,†,†,†,†,†,†
3,ACTON-AGUA DULCE UNIFIED,California,1,70,221,38,362,–,61,1,...,288,1,49,4,15,319,96,233,5,71

In [55]:
df.iloc[:,2:] = df.iloc[:,2:].apply(pd.to_numeric, errors='coerce')

In [87]:
df_grades = df.copy()
df_school_districts_by_race = df.copy().iloc[:,:1]
df_school_districts_by_race

                          Agency Name
0                         ABC UNIFIED
1                 ACALANES UNION HIGH
2                    ACKERMAN CHARTER
3            ACTON-AGUA DULCE UNIFIED
4                 ADELANTO ELEMENTARY
...                               ...
1156           YREKA UNION ELEMENTARY
1157                 YREKA UNION HIGH
1158                YUBA CITY UNIFIED
1159  YUBA COUNTY OFFICE OF EDUCATION
1160   YUCAIPA-CALIMESA JOINT UNIFIED

[1161 rows x 1 columns]

In [93]:
american_indian = ['Grade 6 Students - American Indian/Alaska Native [District] 2016-17', 
           'Grade 7 Students - American Indian/Alaska Native [District] 2016-17', 
           'Grade 8 Students - American Indian/Alaska Native [District] 2016-17',
           'Grade 9 Students - American Indian/Alaska Native [District] 2016-17']
asian = ['Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17', 
           'Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17', 
           'Grade 8 Students - Asian or Asian/Pacific Islander [District] 2016-17',
           'Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17']

df_school_districts_by_race['American Indian/Alaska Native'] = df_grades[american_indian].sum(axis=1)
df_school_districts_by_race['Asian or Asian/Pacific Islander'] = df_grades[asian].sum(axis=1)

In [94]:
df_school_districts_by_race

,Agency Name,American Indian/Alaska Native,Asian or Asian/Pacific Islander
0,ABC UNIFIED,18.0,2356.0
1,ACALANES UNION HIGH,1.0,200.0
2,ACKERMAN CHARTER,1.0,6.0
3,ACTON-AGUA DULCE UNIFIED,10.0,128.0
4,ADELANTO ELEMENTARY,10.0,46.0
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,0.0,0.0
6,ALAMEDA COUNTY OFFICE OF EDUCATION,3.0,27.0
7,ALAMEDA UNIFIED,6.0,1230.0
8,ALBANY CITY UNIFIED,1.0,344.0
9,ALEXANDER VALLEY UNION ELEMENTARY,0.0,0.0
10,ALHAMBRA UNIFIED,7.0,2755.0
11,ALISAL UNION,0.0,20.0
12,ALLENSWORTH ELEMENTARY,0.0,0.0
13,ALPAUGH UNIFIED,0.0,4.0
14,ALPINE COUNTY OFFICE OF EDUCATION,0.0,0.0
15,ALPINE COUNTY UNIFIED,10.0,0.0
16,ALPINE UNION ELEMENTARY,34.0,18.0
17,ALTA LOMA ELEMENTARY,6.0,191.0
18,ALTA VISTA ELEMENTARY,2.0,2.0
19,ALTA-DUTCH FLAT UNION ELEMENTARY,0.0,1.0
20,ALUM ROCK UNION ELEMENTARY,5.0,737.0
21,ALVIEW-DAIRYLAND UNION ELEMENTARY,0.0,3.0
22,ALVINA ELEMENTARY,2.0,0.0
23,ALVORD UNIFIED,8.0,281.0
24,AMADOR COUNTY OFFICE OF EDUCATION,4.0,0.0
25,AMADOR COUNTY ROP,0.0,0.0
26,AMADOR COUNTY UNIFIED,27.0,10.0
27,ANAHEIM ELEMENTARY,2.0,155.0
28,ANAHEIM UNION HIGH,54.0,2476.0
29,ANDERSON UNION HIGH,23.0,14.0
...,...,...,...
1131,WHITTIER CITY ELEMENTARY,4.0,13.0
1132,WHITTIER UNION HIGH,3.0,70.0
1133,WILLIAM (R) ROUSE ROP,0.0,0.0
1134,WILLIAM S. HART UNION HIGH,34.0,1410.0
1135,WILLIAMS UNIFIED,0.0,8.0
1136,WILLITS UNIFIED,46.0,9.0
1137,WILLOW CREEK ELEMENTARY,0.0,0.0
1138,WILLOW GROVE UNION ELEMENTARY,0.0,0.0
1139,WILLOWS UNIFIED,15.0,24.0
1140,WILMAR UNION ELEMENTARY,0.0,0.0
1141,WILSONA ELEMENTARY,5.0,1.0
1142,WINDSOR UNIFIED,23.0,31.0
1143,WINSHIP-ROBBINS,3.0,8.0
1144,WINTERS JOINT UNIFIED,3.0,5.0
1145,WINTON,3.0,28.0
1146,WISEBURN UNIFIED,2.0,78.0
1147,WOODLAKE UNIFIED,2.0,4.0
1148,WOODLAND JOINT UNIFIED,16.0,157.0
1149,WOODSIDE ELEMENTARY,0.0,6.0
1150,WOODVILLE UNION ELEMENTARY,0.0,0.0
1151,WRIGHT ELEMENTARY,1.0,29.0
1152,YOLO COUNTY OFFICE OF EDUCATION,1.0,3.0
1153,YOLO COUNTY ROP,0.0,0.0
1154,YOSEMITE ROP,0.0,0.0
1155,YOSEMITE UNIFIED,27.0,8.0
1156,YREKA UNION ELEMENTARY,37.0,7.0
1157,YREKA UNION HIGH,12.0,0.0
1158,YUBA CITY UNIFIED,19.0,798.0
1159,YUBA COUNTY OFFICE OF EDUCATION,9.0,1.0
1160,YUCAIPA-CALIMESA JOINT UNIFIED,11.0,53.0