In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy

# Fetching the relevant data
## Data wrangling

The process of transforming and mapping data from one "raw" data form into another format with the intent of making it more appropriate and valuable for a variety of downstream purposes such as analytics.

The goal here is to join the 3 datasets containing enrollment from prek to grade 12 into one dataframe.

# Prekindergarten to grade 5:

In [2]:
# load the data into a dataframe

df_pk_g5 = pd.read_csv('ELSI_California_district_enrollment_ethnicity_2016_2017-PK_G5.csv')
df_pk_g5.head(10)

,Agency Name,State Name [District] Latest available year,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,...,Grade 4 Students - White [District] 2016-17,Grade 4 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 4 Students - Two or More Races [District] 2016-17,Grade 5 Students - American Indian/Alaska Native [District] 2016-17,Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 5 Students - Hispanic [District] 2016-17,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17
0,ABC UNIFIED,California,†,†,†,†,†,†,†,9,...,108,9,56,4,546,754,149,96,11,49
1,ACALANES UNION HIGH,California,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
2,ACKERMAN CHARTER,California,†,†,†,†,†,†,†,–,...,49,–,4,–,1,8,1,54,–,2
3,ACTON-AGUA DULCE UNIFIED,California,†,†,†,†,†,†,†,2,...,392,–,110,3,58,263,41,414,2,75
4,ADELANTO ELEMENTARY,California,†,†,†,†,†,†,†,2,...,67,8,49,3,15,604,198,95,8,55
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,California,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
6,ALAMEDA COUNTY OFFICE OF EDUCATION,California,†,†,†,†,†,†,†,3,...,34,7,31,–,27,156,29,16,4,29
7,ALAMEDA UNIFIED,California,†,†,†,†,†,†,†,2,...,260,8,106,4,213,144,61,271,6,82
8,ALBANY CITY UNIFIED,California,†,†,†,†,†,†,†,–,...,97,–,53,–,75,51,7,96,1,37
9,ALEXANDER VALLEY UNION ELEMENTARY,California,†,†,†,†,†,†,†,–,...,12,–,–,–,–,8,–,10,–,–

In [3]:
df_pk_g5.columns

Index(['Agency Name', 'State Name [District] Latest available year',
       'Prekindergarten Students - American Indian/Alaska Native [District] 2016-17',
       'Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Prekindergarten Students - Hispanic [District] 2016-17',
       'Prekindergarten Students - Black [District] 2016-17',
       'Prekindergarten Students - White [District] 2016-17',
       'Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Prekindergarten Students Two or More Races [District] 2016-17',
       'Kindergarten Students - American Indian/Alaska Native [District] 2016-17',
       'Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Kindergarten Students - Hispanic [District] 2016-17',
       'Kindergarten Students - Black [District] 2016-17',
       'Kindergarten Students White [District] 2016-17',
       'Kindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Kindergarten Students Two or More Races [District] 2016-17',
       'Grade 1 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 1 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 1 Students - Hispanic [District] 2016-17',
       'Grade 1 Students - Black [District] 2016-17',
       'Grade 1 Students - White [District] 2016-17',
       'Grade 1 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 1 Students - Two or More Races [District] 2016-17',
       'Grade 2 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 2 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 2 Students - Hispanic [District] 2016-17',
       'Grade 2 Students - Black [District] 2016-17',
       'Grade 2 Students - White [District] 2016-17',
       'Grade 2 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 2 Students - Two or More Races [District] 2016-17',
       'Grade 3 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 3 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 3 Students - Hispanic [District] 2016-17',
       'Grade 3 Students - Black [District] 2016-17',
       'Grade 3 Students - White [District] 2016-17',
       'Grade 3 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 3 Students - Two or More Races [District] 2016-17',
       'Grade 4 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 4 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 4 Students - Hispanic [District] 2016-17',
       'Grade 4 Students - Black [District] 2016-17',
       'Grade 4 Students - White [District] 2016-17',
       'Grade 4 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 4 Students - Two or More Races [District] 2016-17',
       'Grade 5 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 5 Students - Hispanic [District] 2016-17',
       'Grade 5 Students - Black [District] 2016-17',
       'Grade 5 Students - White [District] 2016-17',
       'Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 5 Students - Two or More Races [District] 2016-17'],
      dtype='object')

In [4]:
df_pk5_race = df_pk_g5.iloc[:,2:].apply(pd.to_numeric, errors='coerce')
df_pk5_race

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 4 Students - White [District] 2016-17,Grade 4 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 4 Students - Two or More Races [District] 2016-17,Grade 5 Students - American Indian/Alaska Native [District] 2016-17,Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 5 Students - Hispanic [District] 2016-17,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,108.0,9.0,56.0,4.0,546.0,754.0,149.0,96.0,11.0,49.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,49.0,NaN,4.0,NaN,1.0,8.0,1.0,54.0,NaN,2.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,392.0,NaN,110.0,3.0,58.0,263.0,41.0,414.0,2.0,75.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,67.0,8.0,49.0,3.0,15.0,604.0,198.0,95.0,8.0,55.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_pk5_race['Total Prek-5 American Indian/Alaska Native'] = df_pk5_race[['Prekindergarten Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Kindergarten Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 1 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 2 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 3 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 4 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 5 Students - American Indian/Alaska Native [District] 2016-17']].sum(axis=1)
df_pk5_race.head()

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 4 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 4 Students - Two or More Races [District] 2016-17,Grade 5 Students - American Indian/Alaska Native [District] 2016-17,Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 5 Students - Hispanic [District] 2016-17,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17,Total Prek-5 American Indian/Alaska Native
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,9.0,56.0,4.0,546.0,754.0,149.0,96.0,11.0,49.0,33.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,4.0,NaN,1.0,8.0,1.0,54.0,NaN,2.0,1.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,NaN,110.0,3.0,58.0,263.0,41.0,414.0,2.0,75.0,15.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,8.0,49.0,3.0,15.0,604.0,198.0,95.0,8.0,55.0,21.0

In [6]:
df_pk5_race['Total Prek-5 Asian or Asian/Pacific Islander'] = df_pk5_race[['Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 1 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 2 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 3 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 4 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17']].sum(axis=1)
df_pk5_race.head()

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 4 Students - Two or More Races [District] 2016-17,Grade 5 Students - American Indian/Alaska Native [District] 2016-17,Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 5 Students - Hispanic [District] 2016-17,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,56.0,4.0,546.0,754.0,149.0,96.0,11.0,49.0,33.0,3092.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,4.0,NaN,1.0,8.0,1.0,54.0,NaN,2.0,1.0,3.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,110.0,3.0,58.0,263.0,41.0,414.0,2.0,75.0,15.0,356.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,49.0,3.0,15.0,604.0,198.0,95.0,8.0,55.0,21.0,84.0

In [7]:
df_pk5_race['Total Prek-5 Black'] = df_pk5_race[['Prekindergarten Students - Black [District] 2016-17',
                                                                     'Kindergarten Students - Black [District] 2016-17',
                                                                     'Grade 1 Students - Black [District] 2016-17',
                                                                     'Grade 2 Students - Black [District] 2016-17',
                                                                     'Grade 3 Students - Black [District] 2016-17',
                                                                     'Grade 4 Students - Black [District] 2016-17',
                                                                     'Grade 5 Students - Black [District] 2016-17']].sum(axis=1)
df_pk5_race.head()

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 5 Students - American Indian/Alaska Native [District] 2016-17,Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 5 Students - Hispanic [District] 2016-17,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,4.0,546.0,754.0,149.0,96.0,11.0,49.0,33.0,3092.0,751.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,1.0,8.0,1.0,54.0,NaN,2.0,1.0,3.0,3.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,3.0,58.0,263.0,41.0,414.0,2.0,75.0,15.0,356.0,252.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,3.0,15.0,604.0,198.0,95.0,8.0,55.0,21.0,84.0,1219.0

In [8]:
df_pk5_race['Total Prek-5 Hispanic'] = df_pk5_race[['Prekindergarten Students - Hispanic [District] 2016-17',
                                                                     'Kindergarten Students - Hispanic [District] 2016-17',
                                                                     'Grade 1 Students - Hispanic [District] 2016-17',
                                                                     'Grade 2 Students - Hispanic [District] 2016-17',
                                                                     'Grade 3 Students - Hispanic [District] 2016-17',
                                                                     'Grade 4 Students - Hispanic [District] 2016-17',
                                                                     'Grade 5 Students - Hispanic [District] 2016-17']].sum(axis=1)
df_pk5_race.head()

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 5 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 5 Students - Hispanic [District] 2016-17,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,546.0,754.0,149.0,96.0,11.0,49.0,33.0,3092.0,751.0,4342.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,1.0,8.0,1.0,54.0,NaN,2.0,1.0,3.0,3.0,56.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,58.0,263.0,41.0,414.0,2.0,75.0,15.0,356.0,252.0,1497.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,15.0,604.0,198.0,95.0,8.0,55.0,21.0,84.0,1219.0,3550.0

In [9]:
df_pk5_race['Total Prek-5 White'] = df_pk5_race[['Prekindergarten Students - White [District] 2016-17',
                                                                     'Kindergarten Students White [District] 2016-17',
                                                                     'Grade 1 Students - White [District] 2016-17',
                                                                     'Grade 2 Students - White [District] 2016-17',
                                                                     'Grade 3 Students - White [District] 2016-17',
                                                                     'Grade 4 Students - White [District] 2016-17',
                                                                     'Grade 5 Students - White [District] 2016-17']].sum(axis=1)
df_pk5_race.head()

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 5 Students - Hispanic [District] 2016-17,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,754.0,149.0,96.0,11.0,49.0,33.0,3092.0,751.0,4342.0,582.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,8.0,1.0,54.0,NaN,2.0,1.0,3.0,3.0,56.0,318.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,263.0,41.0,414.0,2.0,75.0,15.0,356.0,252.0,1497.0,2319.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,604.0,198.0,95.0,8.0,55.0,21.0,84.0,1219.0,3550.0,483.0

In [10]:
df_pk5_race['Total Prek-5 Hawaiian Nat./Pacific Isl.'] = df_pk5_race[['Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Kindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 1 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 2 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 3 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 4 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17']].sum(axis=1)
df_pk5_race.head()

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 5 Students - Black [District] 2016-17,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White,Total Prek-5 Hawaiian Nat./Pacific Isl.
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,149.0,96.0,11.0,49.0,33.0,3092.0,751.0,4342.0,582.0,63.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,1.0,54.0,NaN,2.0,1.0,3.0,3.0,56.0,318.0,0.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,41.0,414.0,2.0,75.0,15.0,356.0,252.0,1497.0,2319.0,5.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,198.0,95.0,8.0,55.0,21.0,84.0,1219.0,3550.0,483.0,50.0

In [11]:
df_pk5_race['Total Prek-5 Two or More Races'] = df_pk5_race[['Prekindergarten Students Two or More Races [District] 2016-17',
                                                                     'Kindergarten Students Two or More Races [District] 2016-17',
                                                                     'Grade 1 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 2 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 3 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 4 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 5 Students - Two or More Races [District] 2016-17']].sum(axis=1)
df_pk5_race.head()

,Prekindergarten Students - American Indian/Alaska Native [District] 2016-17,Prekindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Prekindergarten Students - Hispanic [District] 2016-17,Prekindergarten Students - Black [District] 2016-17,Prekindergarten Students - White [District] 2016-17,Prekindergarten Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Prekindergarten Students Two or More Races [District] 2016-17,Kindergarten Students - American Indian/Alaska Native [District] 2016-17,Kindergarten Students - Asian or Asian/Pacific Islander [District] 2016-17,Kindergarten Students - Hispanic [District] 2016-17,...,Grade 5 Students - White [District] 2016-17,Grade 5 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 5 Students - Two or More Races [District] 2016-17,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White,Total Prek-5 Hawaiian Nat./Pacific Isl.,Total Prek-5 Two or More Races
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,543.0,748.0,...,96.0,11.0,49.0,33.0,3092.0,751.0,4342.0,582.0,63.0,272.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,54.0,NaN,2.0,1.0,3.0,3.0,56.0,318.0,0.0,28.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,67.0,285.0,...,414.0,2.0,75.0,15.0,356.0,252.0,1497.0,2319.0,5.0,591.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,9.0,650.0,...,95.0,8.0,55.0,21.0,84.0,1219.0,3550.0,483.0,50.0,307.0

In [12]:
df_pk5_totals = df_pk5_race.drop(df_pk5_race.columns[0:-7], axis = 1)
df_pk5_totals

,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White,Total Prek-5 Hawaiian Nat./Pacific Isl.,Total Prek-5 Two or More Races
0,33.0,3092.0,751.0,4342.0,582.0,63.0,272.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,3.0,3.0,56.0,318.0,0.0,28.0
3,15.0,356.0,252.0,1497.0,2319.0,5.0,591.0
4,21.0,84.0,1219.0,3550.0,483.0,50.0,307.0
...,...,...,...,...,...,...,...
1163,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
df_pk5_totals['Total Enrollment pk-5'] = df_pk5_totals.sum(axis=1)
df_pk5_totals

,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White,Total Prek-5 Hawaiian Nat./Pacific Isl.,Total Prek-5 Two or More Races,Total Enrollment pk-5
0,33.0,3092.0,751.0,4342.0,582.0,63.0,272.0,9135.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,3.0,3.0,56.0,318.0,0.0,28.0,409.0
3,15.0,356.0,252.0,1497.0,2319.0,5.0,591.0,5035.0
4,21.0,84.0,1219.0,3550.0,483.0,50.0,307.0,5714.0
...,...,...,...,...,...,...,...,...
1163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
agency_name = df_pk_g5.iloc[:, :1]
agency_name

                                            Agency Name
0                                           ABC UNIFIED
1                                   ACALANES UNION HIGH
2                                      ACKERMAN CHARTER
3                              ACTON-AGUA DULCE UNIFIED
4                                   ADELANTO ELEMENTARY
...                                                 ...
1163  Data Source: U.S. Department of Education Nati...
1164                                                NaN
1165      † indicates that the data are not applicable.
1166             – indicates that the data are missing.
1167  ‡ indicates that the data do not meet NCES dat...

[1168 rows x 1 columns]

In [15]:
total_enrollment_pk5 = pd.merge(agency_name, df_pk5_totals, left_index=True, right_index=True)
total_enrollment_pk5

,Agency Name,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White,Total Prek-5 Hawaiian Nat./Pacific Isl.,Total Prek-5 Two or More Races,Total Enrollment pk-5
0,ABC UNIFIED,33.0,3092.0,751.0,4342.0,582.0,63.0,272.0,9135.0
1,ACALANES UNION HIGH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ACKERMAN CHARTER,1.0,3.0,3.0,56.0,318.0,0.0,28.0,409.0
3,ACTON-AGUA DULCE UNIFIED,15.0,356.0,252.0,1497.0,2319.0,5.0,591.0,5035.0
4,ADELANTO ELEMENTARY,21.0,84.0,1219.0,3550.0,483.0,50.0,307.0,5714.0
...,...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Grade 6 to grade 9:

In [16]:
# load the data into a dataframe 

df_g6_g9 = pd.read_csv('ELSI_csv_California_district_enrollment_ethnicity_2016_2017_G6-9.csv')
df_g6_g9.head(10)

,Agency Name,State Name [District] Latest available year,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,...,Grade 8 Students - White [District] 2016-17,Grade 8 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 8 Students - Two or More Races [District] 2016-17,Grade 9 Students - American Indian/Alaska Native [District] 2016-17,Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17
0,ABC UNIFIED,California,3,562,777,116,110,10,53,4,...,109,16,31,8,608,710,171,92,14,37
1,ACALANES UNION HIGH,California,†,†,†,†,†,†,†,†,...,†,†,†,1,200,129,27,896,3,110
2,ACKERMAN CHARTER,California,1,2,5,1,49,–,4,–,...,44,–,2,†,†,†,†,†,†,†
3,ACTON-AGUA DULCE UNIFIED,California,1,70,221,38,362,–,61,1,...,288,1,49,4,15,319,96,233,5,71
4,ADELANTO ELEMENTARY,California,2,15,612,208,89,10,41,2,...,75,8,46,2,1,205,67,74,2,27
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,California,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
6,ALAMEDA COUNTY OFFICE OF EDUCATION,California,1,22,119,18,16,–,19,–,...,–,–,2,1,2,70,48,5,1,2
7,ALAMEDA UNIFIED,California,1,267,140,68,252,5,112,2,...,261,13,57,2,341,155,91,239,4,52
8,ALBANY CITY UNIFIED,California,–,73,60,6,105,1,51,–,...,124,1,29,–,87,49,8,101,–,32
9,ALEXANDER VALLEY UNION ELEMENTARY,California,–,–,8,–,8,–,–,†,...,†,†,†,†,†,†,†,†,†,†

In [17]:
df_g6_g9.columns

Index(['Agency Name', 'State Name [District] Latest available year',
       'Grade 6 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 6 Students - Hispanic [District] 2016-17',
       'Grade 6 Students - Black [District] 2016-17',
       'Grade 6 Students - White [District] 2016-17',
       'Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 6 Students - Two or More Races [District] 2016-17',
       'Grade 7 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 7 Students - Hispanic [District] 2016-17',
       'Grade 7 Students - Black [District] 2016-17',
       'Grade 7 Students - White [District] 2016-17',
       'Grade 7 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 7 Students - Two or More Races [District] 2016-17',
       'Grade 8 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 8 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 8 Students - Hispanic [District] 2016-17',
       'Grade 8 Students - Black [District] 2016-17',
       'Grade 8 Students - White [District] 2016-17',
       'Grade 8 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 8 Students - Two or More Races [District] 2016-17',
       'Grade 9 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 9 Students - Hispanic [District] 2016-17',
       'Grade 9 Students - Black [District] 2016-17',
       'Grade 9 Students - White [District] 2016-17',
       'Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 9 Students - Two or More Races [District] 2016-17'],
      dtype='object')

In [18]:
df_total_g6_9 = df_g6_g9.iloc[:,2:].apply(pd.to_numeric, errors='coerce')
df_total_g6_9

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 8 Students - White [District] 2016-17,Grade 8 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 8 Students - Two or More Races [District] 2016-17,Grade 9 Students - American Indian/Alaska Native [District] 2016-17,Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,109.0,16.0,31.0,8.0,608.0,710.0,171.0,92.0,14.0,37.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,200.0,129.0,27.0,896.0,3.0,110.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,44.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,288.0,1.0,49.0,4.0,15.0,319.0,96.0,233.0,5.0,71.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,75.0,8.0,46.0,2.0,1.0,205.0,67.0,74.0,2.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_total_g6_9['Total grade 6-9 American Indian/Alaska Native'] = df_total_g6_9[['Grade 6 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 7 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 8 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 9 Students - American Indian/Alaska Native [District] 2016-17']].sum(axis=1)
df_total_g6_9.head()

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 8 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 8 Students - Two or More Races [District] 2016-17,Grade 9 Students - American Indian/Alaska Native [District] 2016-17,Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17,Total grade 6-9 American Indian/Alaska Native
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,16.0,31.0,8.0,608.0,710.0,171.0,92.0,14.0,37.0,18.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,200.0,129.0,27.0,896.0,3.0,110.0,1.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,1.0,49.0,4.0,15.0,319.0,96.0,233.0,5.0,71.0,10.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,8.0,46.0,2.0,1.0,205.0,67.0,74.0,2.0,27.0,10.0

In [20]:
df_total_g6_9['Total grade 6-9 Asian or Asian/Pacific Islander'] = df_total_g6_9[['Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 8 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17']].sum(axis=1)
df_total_g6_9.head()

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 8 Students - Two or More Races [District] 2016-17,Grade 9 Students - American Indian/Alaska Native [District] 2016-17,Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,31.0,8.0,608.0,710.0,171.0,92.0,14.0,37.0,18.0,2356.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,200.0,129.0,27.0,896.0,3.0,110.0,1.0,200.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.0
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,49.0,4.0,15.0,319.0,96.0,233.0,5.0,71.0,10.0,128.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,46.0,2.0,1.0,205.0,67.0,74.0,2.0,27.0,10.0,46.0

In [21]:
df_total_g6_9['Total grade 6-9 Hispanic'] = df_total_g6_9[['Grade 6 Students - Hispanic [District] 2016-17',
                                                                     'Grade 7 Students - Hispanic [District] 2016-17',
                                                                     'Grade 8 Students - Hispanic [District] 2016-17',
                                                                     'Grade 9 Students - Hispanic [District] 2016-17']].sum(axis=1)
df_total_g6_9.head()

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 9 Students - American Indian/Alaska Native [District] 2016-17,Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,8.0,608.0,710.0,171.0,92.0,14.0,37.0,18.0,2356.0,2956.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,200.0,129.0,27.0,896.0,3.0,110.0,1.0,200.0,129.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.0,18.0
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,4.0,15.0,319.0,96.0,233.0,5.0,71.0,10.0,128.0,950.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,2.0,1.0,205.0,67.0,74.0,2.0,27.0,10.0,46.0,1933.0

In [22]:
df_total_g6_9['Total grade 6-9 Black'] = df_total_g6_9[['Grade 6 Students - Black [District] 2016-17',
                                                                     'Grade 7 Students - Black [District] 2016-17',
                                                                     'Grade 8 Students - Black [District] 2016-17',
                                                                     'Grade 9 Students - Black [District] 2016-17']].sum(axis=1)
df_total_g6_9.head()

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 9 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,608.0,710.0,171.0,92.0,14.0,37.0,18.0,2356.0,2956.0,558.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,200.0,129.0,27.0,896.0,3.0,110.0,1.0,200.0,129.0,27.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,6.0,18.0,1.0
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,15.0,319.0,96.0,233.0,5.0,71.0,10.0,128.0,950.0,200.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,1.0,205.0,67.0,74.0,2.0,27.0,10.0,46.0,1933.0,688.0

In [23]:
df_total_g6_9['Total grade 6-9 White'] = df_total_g6_9[['Grade 6 Students - White [District] 2016-17',
                                                                     'Grade 7 Students - White [District] 2016-17',
                                                                     'Grade 8 Students - White [District] 2016-17',
                                                                     'Grade 9 Students - White [District] 2016-17']].sum(axis=1)
df_total_g6_9.head()

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 9 Students - Hispanic [District] 2016-17,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black,Total grade 6-9 White
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,710.0,171.0,92.0,14.0,37.0,18.0,2356.0,2956.0,558.0,406.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,129.0,27.0,896.0,3.0,110.0,1.0,200.0,129.0,27.0,896.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,NaN,NaN,NaN,NaN,NaN,1.0,6.0,18.0,1.0,142.0
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,319.0,96.0,233.0,5.0,71.0,10.0,128.0,950.0,200.0,1185.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,205.0,67.0,74.0,2.0,27.0,10.0,46.0,1933.0,688.0,315.0

In [24]:
df_total_g6_9['Total grade 6-9 Hawaiian Nat./Pacific Isl.'] = df_total_g6_9[['Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 7 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 8 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17']].sum(axis=1)
df_total_g6_9.head()

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 9 Students - Black [District] 2016-17,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black,Total grade 6-9 White,Total grade 6-9 Hawaiian Nat./Pacific Isl.
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,171.0,92.0,14.0,37.0,18.0,2356.0,2956.0,558.0,406.0,57.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.0,896.0,3.0,110.0,1.0,200.0,129.0,27.0,896.0,3.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,NaN,NaN,NaN,NaN,1.0,6.0,18.0,1.0,142.0,0.0
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,96.0,233.0,5.0,71.0,10.0,128.0,950.0,200.0,1185.0,8.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,67.0,74.0,2.0,27.0,10.0,46.0,1933.0,688.0,315.0,36.0

In [25]:
df_total_g6_9['Total grade 6-9 Two or More Races'] = df_total_g6_9[['Grade 6 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 7 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 8 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 9 Students - Two or More Races [District] 2016-17']].sum(axis=1)
df_total_g6_9.head()

,Grade 6 Students - American Indian/Alaska Native [District] 2016-17,Grade 6 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 6 Students - Hispanic [District] 2016-17,Grade 6 Students - Black [District] 2016-17,Grade 6 Students - White [District] 2016-17,Grade 6 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 6 Students - Two or More Races [District] 2016-17,Grade 7 Students - American Indian/Alaska Native [District] 2016-17,Grade 7 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 7 Students - Hispanic [District] 2016-17,...,Grade 9 Students - White [District] 2016-17,Grade 9 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 9 Students - Two or More Races [District] 2016-17,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black,Total grade 6-9 White,Total grade 6-9 Hawaiian Nat./Pacific Isl.,Total grade 6-9 Two or More Races
0,3.0,562.0,777.0,116.0,110.0,10.0,53.0,4.0,592.0,711.0,...,92.0,14.0,37.0,18.0,2356.0,2956.0,558.0,406.0,57.0,159.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,896.0,3.0,110.0,1.0,200.0,129.0,27.0,896.0,3.0,110.0
2,1.0,2.0,5.0,1.0,49.0,NaN,4.0,NaN,2.0,8.0,...,NaN,NaN,NaN,1.0,6.0,18.0,1.0,142.0,0.0,9.0
3,1.0,70.0,221.0,38.0,362.0,NaN,61.0,1.0,25.0,188.0,...,233.0,5.0,71.0,10.0,128.0,950.0,200.0,1185.0,8.0,240.0
4,2.0,15.0,612.0,208.0,89.0,10.0,41.0,2.0,13.0,611.0,...,74.0,2.0,27.0,10.0,46.0,1933.0,688.0,315.0,36.0,153.0

In [26]:
df_g6to9_totals = df_total_g6_9.drop(df_total_g6_9.columns[0:-7], axis = 1)
df_g6to9_totals

,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black,Total grade 6-9 White,Total grade 6-9 Hawaiian Nat./Pacific Isl.,Total grade 6-9 Two or More Races
0,18.0,2356.0,2956.0,558.0,406.0,57.0,159.0
1,1.0,200.0,129.0,27.0,896.0,3.0,110.0
2,1.0,6.0,18.0,1.0,142.0,0.0,9.0
3,10.0,128.0,950.0,200.0,1185.0,8.0,240.0
4,10.0,46.0,1933.0,688.0,315.0,36.0,153.0
...,...,...,...,...,...,...,...
1163,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
df_g6to9_totals['Total Enrollment G6 to G9'] = df_g6to9_totals.sum(axis=1)
df_g6to9_totals

,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black,Total grade 6-9 White,Total grade 6-9 Hawaiian Nat./Pacific Isl.,Total grade 6-9 Two or More Races,Total Enrollment G6 to G9
0,18.0,2356.0,2956.0,558.0,406.0,57.0,159.0,6510.0
1,1.0,200.0,129.0,27.0,896.0,3.0,110.0,1366.0
2,1.0,6.0,18.0,1.0,142.0,0.0,9.0,177.0
3,10.0,128.0,950.0,200.0,1185.0,8.0,240.0,2721.0
4,10.0,46.0,1933.0,688.0,315.0,36.0,153.0,3181.0
...,...,...,...,...,...,...,...,...
1163,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
total_enrollment_g6g9 = pd.merge(agency_name, df_g6to9_totals, left_index=True, right_index=True)
total_enrollment_g6g9

,Agency Name,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black,Total grade 6-9 White,Total grade 6-9 Hawaiian Nat./Pacific Isl.,Total grade 6-9 Two or More Races,Total Enrollment G6 to G9
0,ABC UNIFIED,18.0,2356.0,2956.0,558.0,406.0,57.0,159.0,6510.0
1,ACALANES UNION HIGH,1.0,200.0,129.0,27.0,896.0,3.0,110.0,1366.0
2,ACKERMAN CHARTER,1.0,6.0,18.0,1.0,142.0,0.0,9.0,177.0
3,ACTON-AGUA DULCE UNIFIED,10.0,128.0,950.0,200.0,1185.0,8.0,240.0,2721.0
4,ADELANTO ELEMENTARY,10.0,46.0,1933.0,688.0,315.0,36.0,153.0,3181.0
...,...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Below a table contaning total enrollment by race from prek to grade 9:

In [29]:
enrollment_pk_9 = pd.merge(total_enrollment_pk5, df_g6to9_totals, left_index=True, right_index=True)
enrollment_pk_9

,Agency Name,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White,Total Prek-5 Hawaiian Nat./Pacific Isl.,Total Prek-5 Two or More Races,Total Enrollment pk-5,Total grade 6-9 American Indian/Alaska Native,Total grade 6-9 Asian or Asian/Pacific Islander,Total grade 6-9 Hispanic,Total grade 6-9 Black,Total grade 6-9 White,Total grade 6-9 Hawaiian Nat./Pacific Isl.,Total grade 6-9 Two or More Races,Total Enrollment G6 to G9
0,ABC UNIFIED,33.0,3092.0,751.0,4342.0,582.0,63.0,272.0,9135.0,18.0,2356.0,2956.0,558.0,406.0,57.0,159.0,6510.0
1,ACALANES UNION HIGH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,200.0,129.0,27.0,896.0,3.0,110.0,1366.0
2,ACKERMAN CHARTER,1.0,3.0,3.0,56.0,318.0,0.0,28.0,409.0,1.0,6.0,18.0,1.0,142.0,0.0,9.0,177.0
3,ACTON-AGUA DULCE UNIFIED,15.0,356.0,252.0,1497.0,2319.0,5.0,591.0,5035.0,10.0,128.0,950.0,200.0,1185.0,8.0,240.0,2721.0
4,ADELANTO ELEMENTARY,21.0,84.0,1219.0,3550.0,483.0,50.0,307.0,5714.0,10.0,46.0,1933.0,688.0,315.0,36.0,153.0,3181.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [30]:
enrollment_pk_9.columns

Index(['Agency Name', 'Total Prek-5 American Indian/Alaska Native',
       'Total Prek-5 Asian or Asian/Pacific Islander', 'Total Prek-5 Black',
       'Total Prek-5 Hispanic', 'Total Prek-5 White',
       'Total Prek-5 Hawaiian Nat./Pacific Isl.',
       'Total Prek-5 Two or More Races', 'Total Enrollment pk-5',
       'Total grade 6-9 American Indian/Alaska Native',
       'Total grade 6-9 Asian or Asian/Pacific Islander',
       'Total grade 6-9 Hispanic', 'Total grade 6-9 Black',
       'Total grade 6-9 White', 'Total grade 6-9 Hawaiian Nat./Pacific Isl.',
       'Total grade 6-9 Two or More Races', 'Total Enrollment G6 to G9'],
      dtype='object')

In [31]:
enrollment_pk_9['Total American Indian/Alaska Native'] = enrollment_pk_9[['Total Prek-5 American Indian/Alaska Native', 
                                                                   'Total grade 6-9 American Indian/Alaska Native']].sum(axis=1)
enrollment_pk_9['Total Black'] = enrollment_pk_9[['Total Prek-5 Black','Total grade 6-9 Black']].sum(axis=1)
enrollment_pk_9['Total Hispanic'] = enrollment_pk_9[['Total Prek-5 Hispanic','Total grade 6-9 Hispanic']].sum(axis=1)
enrollment_pk_9['Total White'] = enrollment_pk_9[['Total Prek-5 White','Total grade 6-9 White']].sum(axis=1)
enrollment_pk_9['Total Hawaiian Nat./Pacific Isl.'] = enrollment_pk_9[['Total Prek-5 Hawaiian Nat./Pacific Isl.',
                                                                 'Total grade 6-9 Hawaiian Nat./Pacific Isl.']].sum(axis=1)
enrollment_pk_9['Total Two or More Races'] = enrollment_pk_9[['Total Prek-5 Two or More Races','Total grade 6-9 Two or More Races']].sum(axis=1)
enrollment_pk_9['Total Asian or Asian/Pacific Islander'] = enrollment_pk_9[['Total Prek-5 Asian or Asian/Pacific Islander','Total grade 6-9 Asian or Asian/Pacific Islander']].sum(axis=1)

enrollment_pk_9.head()

,Agency Name,Total Prek-5 American Indian/Alaska Native,Total Prek-5 Asian or Asian/Pacific Islander,Total Prek-5 Black,Total Prek-5 Hispanic,Total Prek-5 White,Total Prek-5 Hawaiian Nat./Pacific Isl.,Total Prek-5 Two or More Races,Total Enrollment pk-5,Total grade 6-9 American Indian/Alaska Native,...,Total grade 6-9 Hawaiian Nat./Pacific Isl.,Total grade 6-9 Two or More Races,Total Enrollment G6 to G9,Total American Indian/Alaska Native,Total Black,Total Hispanic,Total White,Total Hawaiian Nat./Pacific Isl.,Total Two or More Races,Total Asian or Asian/Pacific Islander
0,ABC UNIFIED,33.0,3092.0,751.0,4342.0,582.0,63.0,272.0,9135.0,18.0,...,57.0,159.0,6510.0,51.0,1309.0,7298.0,988.0,120.0,431.0,5448.0
1,ACALANES UNION HIGH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,3.0,110.0,1366.0,1.0,27.0,129.0,896.0,3.0,110.0,200.0
2,ACKERMAN CHARTER,1.0,3.0,3.0,56.0,318.0,0.0,28.0,409.0,1.0,...,0.0,9.0,177.0,2.0,4.0,74.0,460.0,0.0,37.0,9.0
3,ACTON-AGUA DULCE UNIFIED,15.0,356.0,252.0,1497.0,2319.0,5.0,591.0,5035.0,10.0,...,8.0,240.0,2721.0,25.0,452.0,2447.0,3504.0,13.0,831.0,484.0
4,ADELANTO ELEMENTARY,21.0,84.0,1219.0,3550.0,483.0,50.0,307.0,5714.0,10.0,...,36.0,153.0,3181.0,31.0,1907.0,5483.0,798.0,86.0,460.0,130.0

In [32]:
total_enrollment_byrace = enrollment_pk_9.drop(enrollment_pk_9.columns[1:-7], axis = 1)
total_enrollment_byrace['Total Enrollment'] = total_enrollment_byrace.iloc[:, 1:].sum(axis=1)
total_enrollment_byrace

,Agency Name,Total American Indian/Alaska Native,Total Black,Total Hispanic,Total White,Total Hawaiian Nat./Pacific Isl.,Total Two or More Races,Total Asian or Asian/Pacific Islander,Total Enrollment
0,ABC UNIFIED,51.0,1309.0,7298.0,988.0,120.0,431.0,5448.0,15645.0
1,ACALANES UNION HIGH,1.0,27.0,129.0,896.0,3.0,110.0,200.0,1366.0
2,ACKERMAN CHARTER,2.0,4.0,74.0,460.0,0.0,37.0,9.0,586.0
3,ACTON-AGUA DULCE UNIFIED,25.0,452.0,2447.0,3504.0,13.0,831.0,484.0,7756.0
4,ADELANTO ELEMENTARY,31.0,1907.0,5483.0,798.0,86.0,460.0,130.0,8895.0
...,...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Grade 10 to grade 12:

In [33]:
# load the data into a dataframe

df_g10_g12 = pd.read_csv('ELSI_California_district_enrollment_ethnicity_2016_2017_G10-G12.csv')
df_g10_g12.head(10)

,Agency Name,State Name [District] Latest available year,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,...,Grade 11 Students - White [District] 2016-17,Grade 11 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 11 Students - Two or More Races [District] 2016-17,Grade 12 Students - American Indian/Alaska Native [District] 2016-17,Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 12 Students - Hispanic [District] 2016-17,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17
0,ABC UNIFIED,California,4,623,656,159,100,12,32,–,...,95,15,31,8,701,719,165,119,11,30
1,ACALANES UNION HIGH,California,2,200,144,20,885,2,132,4,...,926,6,84,2,203,94,23,915,5,76
2,ACKERMAN CHARTER,California,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
3,ACTON-AGUA DULCE UNIFIED,California,5,16,316,81,244,3,58,4,...,227,2,76,2,21,367,78,224,–,75
4,ADELANTO ELEMENTARY,California,2,4,325,103,81,1,17,1,...,91,1,26,1,3,188,46,40,–,14
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,California,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†
6,ALAMEDA COUNTY OFFICE OF EDUCATION,California,–,3,81,54,8,2,4,3,...,4,3,4,1,8,103,114,16,1,10
7,ALAMEDA UNIFIED,California,1,315,164,89,241,7,65,6,...,215,9,42,3,363,172,97,217,5,53
8,ALBANY CITY UNIFIED,California,1,95,53,16,98,2,34,1,...,111,1,33,1,84,50,15,120,–,30
9,ALEXANDER VALLEY UNION ELEMENTARY,California,†,†,†,†,†,†,†,†,...,†,†,†,†,†,†,†,†,†,†

In [34]:
df_g10_g12.columns

Index(['Agency Name', 'State Name [District] Latest available year',
       'Grade 10 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 10 Students - Hispanic [District] 2016-17',
       'Grade 10 Students - Black [District] 2016-17',
       'Grade 10 Students - White [District] 2016-17',
       'Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 10 Students - Two or More Races [District] 2016-17',
       'Grade 11 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 11 Students - Hispanic [District] 2016-17',
       'Grade 11 Students - Black [District] 2016-17',
       'Grade 11 Students - White [District] 2016-17',
       'Grade 11 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 11 Students - Two or More Races [District] 2016-17',
       'Grade 12 Students - American Indian/Alaska Native [District] 2016-17',
       'Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17',
       'Grade 12 Students - Hispanic [District] 2016-17',
       'Grade 12 Students - Black [District] 2016-17',
       'Grade 12 Students - White [District] 2016-17',
       'Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
       'Grade 12 Students - Two or More Races [District] 2016-17'],
      dtype='object')

In [35]:
df_total = df_g10_g12.iloc[:,2:].apply(pd.to_numeric, errors='coerce')
df_total

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 11 Students - White [District] 2016-17,Grade 11 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 11 Students - Two or More Races [District] 2016-17,Grade 12 Students - American Indian/Alaska Native [District] 2016-17,Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 12 Students - Hispanic [District] 2016-17,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,95.0,15.0,31.0,8.0,701.0,719.0,165.0,119.0,11.0,30.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,926.0,6.0,84.0,2.0,203.0,94.0,23.0,915.0,5.0,76.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,227.0,2.0,76.0,2.0,21.0,367.0,78.0,224.0,NaN,75.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,91.0,1.0,26.0,1.0,3.0,188.0,46.0,40.0,NaN,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df_total['Total G10-G12 American Indian/Alaska Native'] = df_total[['Grade 10 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 11 Students - American Indian/Alaska Native [District] 2016-17',
                                                                     'Grade 12 Students - American Indian/Alaska Native [District] 2016-17']].sum(axis=1)
df_total.head()

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 11 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 11 Students - Two or More Races [District] 2016-17,Grade 12 Students - American Indian/Alaska Native [District] 2016-17,Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 12 Students - Hispanic [District] 2016-17,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17,Total G10-G12 American Indian/Alaska Native
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,15.0,31.0,8.0,701.0,719.0,165.0,119.0,11.0,30.0,12.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,6.0,84.0,2.0,203.0,94.0,23.0,915.0,5.0,76.0,8.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,2.0,76.0,2.0,21.0,367.0,78.0,224.0,NaN,75.0,11.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,1.0,26.0,1.0,3.0,188.0,46.0,40.0,NaN,14.0,4.0

In [37]:
df_total['Total G10-G12 Asian or Asian/Pacific Islander'] = df_total[['Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17',
                                                                     'Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17']].sum(axis=1)
df_total.head()

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 11 Students - Two or More Races [District] 2016-17,Grade 12 Students - American Indian/Alaska Native [District] 2016-17,Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 12 Students - Hispanic [District] 2016-17,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,31.0,8.0,701.0,719.0,165.0,119.0,11.0,30.0,12.0,2011.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,84.0,2.0,203.0,94.0,23.0,915.0,5.0,76.0,8.0,650.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,76.0,2.0,21.0,367.0,78.0,224.0,NaN,75.0,11.0,52.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,26.0,1.0,3.0,188.0,46.0,40.0,NaN,14.0,4.0,9.0

In [38]:
df_total['Total G10-G12 Hispanic'] = df_total[['Grade 10 Students - Hispanic [District] 2016-17',
                                                                     'Grade 11 Students - Hispanic [District] 2016-17',
                                                                     'Grade 12 Students - Hispanic [District] 2016-17']].sum(axis=1)
df_total.head()

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 12 Students - American Indian/Alaska Native [District] 2016-17,Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 12 Students - Hispanic [District] 2016-17,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander,Total G10-G12 Hispanic
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,8.0,701.0,719.0,165.0,119.0,11.0,30.0,12.0,2011.0,2127.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,2.0,203.0,94.0,23.0,915.0,5.0,76.0,8.0,650.0,379.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,2.0,21.0,367.0,78.0,224.0,NaN,75.0,11.0,52.0,1019.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,1.0,3.0,188.0,46.0,40.0,NaN,14.0,4.0,9.0,844.0

In [39]:
df_total['Total G10-G12 Black'] = df_total[['Grade 10 Students - Black [District] 2016-17',
                                                                     'Grade 11 Students - Black [District] 2016-17',
                                                                     'Grade 12 Students - Black [District] 2016-17']].sum(axis=1)
df_total.head()

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 12 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 12 Students - Hispanic [District] 2016-17,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander,Total G10-G12 Hispanic,Total G10-G12 Black
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,701.0,719.0,165.0,119.0,11.0,30.0,12.0,2011.0,2127.0,482.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,203.0,94.0,23.0,915.0,5.0,76.0,8.0,650.0,379.0,68.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,21.0,367.0,78.0,224.0,NaN,75.0,11.0,52.0,1019.0,253.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,3.0,188.0,46.0,40.0,NaN,14.0,4.0,9.0,844.0,249.0

In [40]:
df_total['Total G10-G12 White'] = df_total[['Grade 10 Students - White [District] 2016-17',
                                                                     'Grade 11 Students - White [District] 2016-17',
                                                                     'Grade 12 Students - White [District] 2016-17']].sum(axis=1)
df_total.head()

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 12 Students - Hispanic [District] 2016-17,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander,Total G10-G12 Hispanic,Total G10-G12 Black,Total G10-G12 White
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,719.0,165.0,119.0,11.0,30.0,12.0,2011.0,2127.0,482.0,314.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,94.0,23.0,915.0,5.0,76.0,8.0,650.0,379.0,68.0,2726.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,367.0,78.0,224.0,NaN,75.0,11.0,52.0,1019.0,253.0,695.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,188.0,46.0,40.0,NaN,14.0,4.0,9.0,844.0,249.0,212.0

In [41]:
df_total['Total G10-G12 Hawaiian Nat./Pacific Isl.'] = df_total[['Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 11 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17',
                                                                     'Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17']].sum(axis=1)
df_total.head()

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 12 Students - Black [District] 2016-17,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander,Total G10-G12 Hispanic,Total G10-G12 Black,Total G10-G12 White,Total G10-G12 Hawaiian Nat./Pacific Isl.
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,165.0,119.0,11.0,30.0,12.0,2011.0,2127.0,482.0,314.0,38.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,23.0,915.0,5.0,76.0,8.0,650.0,379.0,68.0,2726.0,13.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,78.0,224.0,NaN,75.0,11.0,52.0,1019.0,253.0,695.0,5.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,46.0,40.0,NaN,14.0,4.0,9.0,844.0,249.0,212.0,2.0

In [42]:
df_total['Total G10-G12 Two or More Races'] = df_total[['Grade 10 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 11 Students - Two or More Races [District] 2016-17',
                                                                     'Grade 12 Students - Two or More Races [District] 2016-17']].sum(axis=1)
df_total.head()

,Grade 10 Students - American Indian/Alaska Native [District] 2016-17,Grade 10 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 10 Students - Hispanic [District] 2016-17,Grade 10 Students - Black [District] 2016-17,Grade 10 Students - White [District] 2016-17,Grade 10 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 10 Students - Two or More Races [District] 2016-17,Grade 11 Students - American Indian/Alaska Native [District] 2016-17,Grade 11 Students - Asian or Asian/Pacific Islander [District] 2016-17,Grade 11 Students - Hispanic [District] 2016-17,...,Grade 12 Students - White [District] 2016-17,Grade 12 Students - Hawaiian Nat./Pacific Isl. [District] 2016-17,Grade 12 Students - Two or More Races [District] 2016-17,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander,Total G10-G12 Hispanic,Total G10-G12 Black,Total G10-G12 White,Total G10-G12 Hawaiian Nat./Pacific Isl.,Total G10-G12 Two or More Races
0,4.0,623.0,656.0,159.0,100.0,12.0,32.0,NaN,687.0,752.0,...,119.0,11.0,30.0,12.0,2011.0,2127.0,482.0,314.0,38.0,93.0
1,2.0,200.0,144.0,20.0,885.0,2.0,132.0,4.0,247.0,141.0,...,915.0,5.0,76.0,8.0,650.0,379.0,68.0,2726.0,13.0,292.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5.0,16.0,316.0,81.0,244.0,3.0,58.0,4.0,15.0,336.0,...,224.0,NaN,75.0,11.0,52.0,1019.0,253.0,695.0,5.0,209.0
4,2.0,4.0,325.0,103.0,81.0,1.0,17.0,1.0,2.0,331.0,...,40.0,NaN,14.0,4.0,9.0,844.0,249.0,212.0,2.0,57.0

In [43]:
df_total = df_total.drop(df_total.columns[0:-7], axis = 1)
df_total

,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander,Total G10-G12 Hispanic,Total G10-G12 Black,Total G10-G12 White,Total G10-G12 Hawaiian Nat./Pacific Isl.,Total G10-G12 Two or More Races
0,12.0,2011.0,2127.0,482.0,314.0,38.0,93.0
1,8.0,650.0,379.0,68.0,2726.0,13.0,292.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,11.0,52.0,1019.0,253.0,695.0,5.0,209.0
4,4.0,9.0,844.0,249.0,212.0,2.0,57.0
...,...,...,...,...,...,...,...
1163,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
total_enrollment_byrace

,Agency Name,Total American Indian/Alaska Native,Total Black,Total Hispanic,Total White,Total Hawaiian Nat./Pacific Isl.,Total Two or More Races,Total Asian or Asian/Pacific Islander,Total Enrollment
0,ABC UNIFIED,51.0,1309.0,7298.0,988.0,120.0,431.0,5448.0,15645.0
1,ACALANES UNION HIGH,1.0,27.0,129.0,896.0,3.0,110.0,200.0,1366.0
2,ACKERMAN CHARTER,2.0,4.0,74.0,460.0,0.0,37.0,9.0,586.0
3,ACTON-AGUA DULCE UNIFIED,25.0,452.0,2447.0,3504.0,13.0,831.0,484.0,7756.0
4,ADELANTO ELEMENTARY,31.0,1907.0,5483.0,798.0,86.0,460.0,130.0,8895.0
...,...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
total_enrollment = pd.merge(total_enrollment_byrace, df_total, left_index=True, right_index=True)
total_enrollment

,Agency Name,Total American Indian/Alaska Native,Total Black,Total Hispanic,Total White,Total Hawaiian Nat./Pacific Isl.,Total Two or More Races,Total Asian or Asian/Pacific Islander,Total Enrollment,Total G10-G12 American Indian/Alaska Native,Total G10-G12 Asian or Asian/Pacific Islander,Total G10-G12 Hispanic,Total G10-G12 Black,Total G10-G12 White,Total G10-G12 Hawaiian Nat./Pacific Isl.,Total G10-G12 Two or More Races
0,ABC UNIFIED,51.0,1309.0,7298.0,988.0,120.0,431.0,5448.0,15645.0,12.0,2011.0,2127.0,482.0,314.0,38.0,93.0
1,ACALANES UNION HIGH,1.0,27.0,129.0,896.0,3.0,110.0,200.0,1366.0,8.0,650.0,379.0,68.0,2726.0,13.0,292.0
2,ACKERMAN CHARTER,2.0,4.0,74.0,460.0,0.0,37.0,9.0,586.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ACTON-AGUA DULCE UNIFIED,25.0,452.0,2447.0,3504.0,13.0,831.0,484.0,7756.0,11.0,52.0,1019.0,253.0,695.0,5.0,209.0
4,ADELANTO ELEMENTARY,31.0,1907.0,5483.0,798.0,86.0,460.0,130.0,8895.0,4.0,9.0,844.0,249.0,212.0,2.0,57.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [46]:
total_enrollment.columns

Index(['Agency Name', 'Total American Indian/Alaska Native', 'Total Black',
       'Total Hispanic', 'Total White', 'Total Hawaiian Nat./Pacific Isl.',
       'Total Two or More Races', 'Total Asian or Asian/Pacific Islander',
       'Total Enrollment', 'Total G10-G12 American Indian/Alaska Native',
       'Total G10-G12 Asian or Asian/Pacific Islander',
       'Total G10-G12 Hispanic', 'Total G10-G12 Black', 'Total G10-G12 White',
       'Total G10-G12 Hawaiian Nat./Pacific Isl.',
       'Total G10-G12 Two or More Races'],
      dtype='object')

In [48]:
total_enrollment['American Indian/Alaska Native'] = total_enrollment[['Total American Indian/Alaska Native', 'Total G10-G12 American Indian/Alaska Native']].sum(axis=1)
total_enrollment['Black'] = total_enrollment[['Total Black', 'Total G10-G12 Black']].sum(axis=1)
total_enrollment['Hispanic'] = total_enrollment[['Total Hispanic', 'Total G10-G12 Hispanic']].sum(axis=1)
total_enrollment['White'] = total_enrollment[['Total White', 'Total G10-G12 White']].sum(axis=1)
total_enrollment['Hawaiian Nat./Pacific Isl.'] = total_enrollment[['Total Hawaiian Nat./Pacific Isl.', 'Total G10-G12 Hawaiian Nat./Pacific Isl.']].sum(axis=1)
total_enrollment['Two or More Races'] = total_enrollment[['Total Two or More Races', 'Total G10-G12 Two or More Races']].sum(axis=1)
total_enrollment['Asian or Asian/Pacific Islander'] = total_enrollment[['Total Asian or Asian/Pacific Islander', 'Total G10-G12 Asian or Asian/Pacific Islander']].sum(axis=1)


total_enrollment

,Agency Name,Total American Indian/Alaska Native,Total Black,Total Hispanic,Total White,Total Hawaiian Nat./Pacific Isl.,Total Two or More Races,Total Asian or Asian/Pacific Islander,Total Enrollment,Total G10-G12 American Indian/Alaska Native,...,Total G10-G12 White,Total G10-G12 Hawaiian Nat./Pacific Isl.,Total G10-G12 Two or More Races,American Indian/Alaska Native,Black,Hispanic,White,Hawaiian Nat./Pacific Isl.,Two or More Races,Asian or Asian/Pacific Islander
0,ABC UNIFIED,51.0,1309.0,7298.0,988.0,120.0,431.0,5448.0,15645.0,12.0,...,314.0,38.0,93.0,63.0,1791.0,9425.0,1302.0,158.0,524.0,7459.0
1,ACALANES UNION HIGH,1.0,27.0,129.0,896.0,3.0,110.0,200.0,1366.0,8.0,...,2726.0,13.0,292.0,9.0,95.0,508.0,3622.0,16.0,402.0,850.0
2,ACKERMAN CHARTER,2.0,4.0,74.0,460.0,0.0,37.0,9.0,586.0,0.0,...,0.0,0.0,0.0,2.0,4.0,74.0,460.0,0.0,37.0,9.0
3,ACTON-AGUA DULCE UNIFIED,25.0,452.0,2447.0,3504.0,13.0,831.0,484.0,7756.0,11.0,...,695.0,5.0,209.0,36.0,705.0,3466.0,4199.0,18.0,1040.0,536.0
4,ADELANTO ELEMENTARY,31.0,1907.0,5483.0,798.0,86.0,460.0,130.0,8895.0,4.0,...,212.0,2.0,57.0,35.0,2156.0,6327.0,1010.0,88.0,517.0,139.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
total_enrollment_new = total_enrollment.drop(total_enrollment.columns[1:-7], axis = 1)
total_enrollment_new

,Agency Name,American Indian/Alaska Native,Black,Hispanic,White,Hawaiian Nat./Pacific Isl.,Two or More Races,Asian or Asian/Pacific Islander
0,ABC UNIFIED,63.0,1791.0,9425.0,1302.0,158.0,524.0,7459.0
1,ACALANES UNION HIGH,9.0,95.0,508.0,3622.0,16.0,402.0,850.0
2,ACKERMAN CHARTER,2.0,4.0,74.0,460.0,0.0,37.0,9.0
3,ACTON-AGUA DULCE UNIFIED,36.0,705.0,3466.0,4199.0,18.0,1040.0,536.0
4,ADELANTO ELEMENTARY,35.0,2156.0,6327.0,1010.0,88.0,517.0,139.0
...,...,...,...,...,...,...,...,...
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
total_enrollment_new['Total Enrollment'] = total_enrollment_new.iloc[:, 1:].sum(axis=1)
total_enrollment_new.head(25)

,Agency Name,American Indian/Alaska Native,Black,Hispanic,White,Hawaiian Nat./Pacific Isl.,Two or More Races,Asian or Asian/Pacific Islander,Total Enrollment
0,ABC UNIFIED,63.0,1791.0,9425.0,1302.0,158.0,524.0,7459.0,41444.0
1,ACALANES UNION HIGH,9.0,95.0,508.0,3622.0,16.0,402.0,850.0,11004.0
2,ACKERMAN CHARTER,2.0,4.0,74.0,460.0,0.0,37.0,9.0,1172.0
3,ACTON-AGUA DULCE UNIFIED,36.0,705.0,3466.0,4199.0,18.0,1040.0,536.0,20000.0
4,ADELANTO ELEMENTARY,35.0,2156.0,6327.0,1010.0,88.0,517.0,139.0,20544.0
5,ALAMEDA CNTY. STUDENT EXCHANGE PROG.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,ALAMEDA COUNTY OFFICE OF EDUCATION,16.0,543.0,1581.0,209.0,33.0,225.0,263.0,5740.0
7,ALAMEDA UNIFIED,33.0,924.0,1897.0,3292.0,85.0,1206.0,3722.0,22318.0
8,ALBANY CITY UNIFIED,5.0,117.0,603.0,1368.0,7.0,522.0,1080.0,7404.0
9,ALEXANDER VALLEY UNION ELEMENTARY,0.0,1.0,48.0,80.0,0.0,1.0,0.0,260.0
10,ALHAMBRA UNIFIED,33.0,112.0,7071.0,349.0,16.0,406.0,9084.0,34142.0
11,ALISAL UNION,4.0,34.0,8414.0,117.0,18.0,517.0,131.0,18470.0
12,ALLENSWORTH ELEMENTARY,0.0,1.0,77.0,0.0,0.0,0.0,0.0,156.0
13,ALPAUGH UNIFIED,4.0,16.0,501.0,213.0,0.0,44.0,15.0,1586.0
14,ALPINE COUNTY OFFICE OF EDUCATION,2.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
15,ALPINE COUNTY UNIFIED,32.0,0.0,4.0,42.0,0.0,2.0,0.0,160.0
16,ALPINE UNION ELEMENTARY,81.0,37.0,400.0,1111.0,7.0,74.0,35.0,3490.0
17,ALTA LOMA ELEMENTARY,31.0,381.0,2676.0,2281.0,28.0,90.0,501.0,11976.0
18,ALTA VISTA ELEMENTARY,4.0,0.0,449.0,76.0,19.0,2.0,5.0,1110.0
19,ALTA-DUTCH FLAT UNION ELEMENTARY,1.0,0.0,6.0,91.0,0.0,5.0,1.0,208.0
20,ALUM ROCK UNION ELEMENTARY,21.0,156.0,9154.0,194.0,97.0,134.0,1868.0,23248.0
21,ALVIEW-DAIRYLAND UNION ELEMENTARY,1.0,0.0,213.0,156.0,0.0,1.0,10.0,762.0
22,ALVINA ELEMENTARY,2.0,0.0,154.0,24.0,1.0,0.0,1.0,364.0
23,ALVORD UNIFIED,40.0,720.0,15161.0,2034.0,85.0,245.0,949.0,38468.0
24,AMADOR COUNTY OFFICE OF EDUCATION,9.0,0.0,51.0,143.0,0.0,19.0,0.0,444.0

In [51]:
total_enrollment_new.tail(25)

,Agency Name,American Indian/Alaska Native,Black,Hispanic,White,Hawaiian Nat./Pacific Isl.,Two or More Races,Asian or Asian/Pacific Islander,Total Enrollment
1143,WINSHIP-ROBBINS,4.0,2.0,245.0,395.0,0.0,74.0,20.0,740.0
1144,WINTERS JOINT UNIFIED,4.0,23.0,1027.0,473.0,2.0,7.0,19.0,1555.0
1145,WINTON,10.0,15.0,1692.0,144.0,0.0,5.0,76.0,1942.0
1146,WISEBURN UNIFIED,9.0,616.0,2227.0,834.0,23.0,377.0,215.0,4301.0
1147,WOODLAKE UNIFIED,6.0,6.0,1999.0,158.0,0.0,6.0,17.0,2192.0
1148,WOODLAND JOINT UNIFIED,54.0,139.0,6843.0,2243.0,36.0,206.0,556.0,10077.0
1149,WOODSIDE ELEMENTARY,0.0,9.0,45.0,283.0,7.0,41.0,15.0,400.0
1150,WOODVILLE UNION ELEMENTARY,0.0,0.0,426.0,9.0,0.0,0.0,1.0,436.0
1151,WRIGHT ELEMENTARY,18.0,47.0,1039.0,314.0,4.0,42.0,129.0,1593.0
1152,YOLO COUNTY OFFICE OF EDUCATION,1.0,9.0,156.0,358.0,2.0,6.0,8.0,540.0
1153,YOLO COUNTY ROP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1154,YOSEMITE ROP,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1155,YOSEMITE UNIFIED,64.0,13.0,411.0,1515.0,1.0,151.0,33.0,2188.0
1156,YREKA UNION ELEMENTARY,149.0,7.0,150.0,574.0,0.0,54.0,25.0,959.0
1157,YREKA UNION HIGH,36.0,5.0,98.0,424.0,0.0,63.0,8.0,634.0
1158,YUBA CITY UNIFIED,86.0,244.0,5869.0,3785.0,44.0,718.0,2538.0,13284.0
1159,YUBA COUNTY OFFICE OF EDUCATION,20.0,18.0,165.0,287.0,2.0,59.0,15.0,566.0
1160,YUCAIPA-CALIMESA JOINT UNIFIED,42.0,153.0,4038.0,4720.0,19.0,807.0,190.0,9969.0
1161,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1162,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1163,Data Source: U.S. Department of Education Nati...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1164,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1165,† indicates that the data are not applicable.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1166,– indicates that the data are missing.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1167,‡ indicates that the data do not meet NCES dat...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0